packages:
  - package
  - playground
  - docs

catalog:
  react: ^19.1.1
  react-dom: ^19.1.1
  "@types/react": ^19.1.10
  "@types/react-dom": ^19.1.7

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@tailwindcss/oxide"
  - esbuild
