packages:
  - package
  - playground

catalog:
  react: ^19.2.0
  react-dom: ^19.2.0
  "@types/react": ^19.2.0
  "@types/react-dom": ^19.2.0

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@tailwindcss/oxide"
  - esbuild
