packages:
  - package
  - playground

catalog:
  react: ^19.2.4
  react-dom: ^19.2.4
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@tailwindcss/oxide"
  - esbuild
