packages:
  - package
  - playground

catalog:
  react: ^19.2.3
  react-dom: ^19.2.3
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@tailwindcss/oxide"
  - esbuild
