packages:
  - package
  - playground

catalog:
  react: ^19.3.0
  react-dom: ^19.3.0
  "@types/react": ^19.3.0
  "@types/react-dom": ^19.3.0

allowBuilds:
  "@biomejs/biome": true
  "@tailwindcss/oxide": true
  esbuild: true

minimumReleaseAgeExclude:
  - vite@8.3.3
