name: Generate changeset for Renovate

on:
  merge_group:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}

      - name: Git Identity
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: pnpm/action-setup@v4.1.0

      - name: Run changesets-renovate
        run: pnpm dlx @scaleway/changesets-renovate
